### ISSUE TITLE
Statut of package?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mastodon_ynh#1]
What is the statut of your app?
Working?
In progress?
Broken?
regarding https://yunohost.org/#/apps_in_progress_en ?

Thank you

**Comment by magikcypress** [comment]
In progress for the moment

**Comment by NicolasPetton** [comment]
@magikcypress if the package is not ready to be used, maybe warn users in the readme?

**Comment by nicopace** [comment]
Is there any way of helping to have this working?
It seems that mastodon is getting a lot of traction and social impact, and it would be great for Yunohost to allow users to install their own instances.

**Comment by magikcypress** [comment]
Yes, we know that it is of interest to many people, but there are still some blocking bugs that prevents us from testing.

We have a problem with sending emails, but @nemsia seems to have found the solution.

You have to fix the problem with the Nginx proxy_pass with a subdir.
Example: `https: //ynh.local/mastodon` return `path=/mastodon`
We should have `path=/`

I don't recommend to start the application in production, this one uses debian backports package.

There is more bug maybe, if you want to test and send many bug, it is possible. For me, this app run successfully on [YunoHost test server](https://github.com/YunoHost/ynh-dev).

**Comment by nicopace** [comment]
Hi @magikcypress, thanks for replying!

The first two seem to be features (very essencial ones, but still). You can still run mastodon without email support, or install it in mastodon.yourdomain.com instead of yourdomain.com/mastodon

What's wrong with using the backports package? Unless those are unmantained, it would be perfectly fine to install them, right?

**Comment by magikcypress** [comment]
Hello @nicopace,

> The first two seem to be features (very essencial ones, but still). You can still run mastodon without email support, or install it in mastodon.yourdomain.com instead of yourdomain.com/mastodon

I will add in the documentation that the user must install mastodon with a domain or sub domain. For now, it's hard to make it work properly with a subdir

> What's wrong with using the backports package? Unless those are unmantained, it would be perfectly fine to install them, right?

The problem is that it is difficult to remove the application without breaking YunoHost. For this, I commented the command lines `apt-get remove ...` in the remove file.
