### ISSUE TITLE
Support for Yunohost 3.x

### ISSUE THREAD

**Issue by HugoPoi** [YunoHost-Apps/mastodon_ynh#106]
Is this package working with Yunohost 3.x ?

**Comment by anmol26s** [comment]
It will be great if you can try a fresh install from develop branch and show logs.
Installation command: 
`$ yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh/tree/develop --debug `

There is a known bug which needs more investigation:
https://github.com/YunoHost-Apps/mastodon_ynh/issues/105

**Comment by HugoPoi** [comment]
I test on my 3.x install and all seems good !
I already have this package installed on my 2.x Yunohost instance then i upgrade to 3.x, and mastodon was broken. I have done `yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh.git` and all seems good. Maybe we can add this info in the README.

**Comment by anmol26s** [comment]
This can be closed. If the @nemsia thinks that this information is required in readme then this can be added in readme. But I don't think its required as Yunohost 3 is now default and most of people have migrated to it. So if have to be supported by default by all packages.

**Comment by nemsia** [comment]
Need to change the readme.md to remove backport warning and yunohost 3 badge.

**Comment by SiM** [comment]
I just try to install mastodon with develop branch (it fails with master branch) on my ynh 3.2 instance.

The installation process is not returning errors but I have a 502 error when getting on my 'mastodon.domain.org'.

mastodon-sidekiq and mastodon-web are running but mastodon-streaming failed to start

A look into the logs : 
> systemd[3136]: mastodon-streaming.service: Failed at step EXEC spawning /usr/bin/npm: No such file or directory
> systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=203/EXEC
> systemd[1]: mastodon-streaming.service: Unit entered failed state.
> systemd[1]: mastodon-streaming.service: Failed with result 'exit-code'.

My server is a raspberry 2 (ARM) and I followed the readme instructions regarding the swap file.

**Comment by anmol26s** [comment]
Maybe you need to upgrade once.

`yunohost app upgrade -u https://github.com/YunoHost-Apps/mastodon_ynh/tree/develop mastodon --debug`

**Comment by SiM** [comment]
After upgrading once, the 502 disappear and I'm able to access mastodon web interface.

But I still have he same problem with mastodon-streaming (same error described in log files :  `Failed at step EXEC spawning /usr/bin/npm: No such file or directory`).

It should be related : the web interface is quite unusable because of 401 errors "Access token invalid"

**Comment by anmol26s** [comment]
install nodejs manually.
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by SiM** [comment]
Thank you for finding a solution @anmol26s, I appreciate. 
But for now I think I will wait that the package become a little more "functional". (Shouldn't be nodejs installed with the install script ?)

**Comment by anmol26s** [comment]
Nodejs is actually installed while install scripts runs. But the mastodon-streaming should use the nodejs path which for the app rather then the global nodejs install path, this is because having many apps using nodejs sometimes conflicts with different version and due to which apps fails. So I started improving develop branch according to the Yunohost 3 when the backup and restore failed for the mastodon master branch for me. 

So present status of mastodon package is that master branch is updated by @nemsia and I use develop branch for myself. But we have to improve the app and merge it to master for more stable package.
I will put the nodejs path which is installed while the install script runs and see if the test are successful, after which I may open a PR for master branch. The other major improvement is LDAP support and some small issues  like https://github.com/YunoHost-Apps/mastodon_ynh/issues/117 which can be fixed later on.

**Comment by SiM** [comment]
Thank you for the explanations.
Yes, LDAP support would be awesome !
I'll keep an eye on this package to test it again, don't hesitate to notify me.

**Comment by Thatoo** [comment]
> Need to change the readme.md to remove backport warning and add yunohost 3 badge.

Do you think this package is ready now for Yunohost 3.x?
Do you think it could get a better yunohost integration badge? right now, it has 0 on https://yunohost.org/apps .and nothing mentioned inside readme.me.
So right now, I would not dare to install it on my server.
I'm also waiting for LDAP support to install Mastodon (and peerube) on my familly yunohost [CHATONS](http://chatons.org/) server.

**Comment by yalh76** [comment]
mastodon_ynh is ready for Yunohost 3.x
