### ISSUE TITLE
Mastodon Password Reset is broken when LDAP authentication is activated

### ISSUE THREAD

**Issue by Doc-Saintly** [YunoHost-Apps/mastodon_ynh#220]
Mastodon allows users to be invited via URL. User accounts created this way cannot reset their password, they get the message: 

> You are logged in via an external service, so password and e-mail settings are not available.

As an admin, I don't have any further options to assist the user with resetting their password.

**Comment by yalh76** [comment]
well I didn't thought about that. Since recently, we have implemented ldap authentication in mastodon_ynh so users don't have a password for mastodon, they use their yunohost login and password.

So with ldap authentication, you can't invite users to your instance, you have to create them a YunoHost User account and password account reset has to be manage using YunoHost.

The only way to manage that would be to ask during install if admin want to user ldap authentication or not.... But the goal was to have ldap authentication for apps....

**Comment by Doc-Saintly** [comment]
Well the account creation process still seems to work. So it seems that Mastodon supports LDAP and internal auth simultaneously? I updated the configuration to disable LDAP and then the user was able to reset their password.

At least for me, I don't want to add YunoHost accounts to everyone I allow to use Mastodon on my server. Is it difficult to support mixed-mode?

**Comment by yalh76** [comment]
Seems a bit difficult to have a mixed-mode with maybe a lot of usecase when an admin will switch from a no-ldap mastodon_ynh to an ldap mastodon...

In addition most of users won't understand a mixed mode and this will request a lot of support that I can't provide.

So If you think you can do a PR for that, feel free to reopen that issue.

**Comment by ehsan0921** [comment]
Hi guys
I'm having this error 
this chapter present the diversity of social sciences sciences  

which part of .env should change??

**Comment by yalh76** [comment]
https://github.com/YunoHost-Apps/mastodon_ynh/blob/cd1f90297bcc490b5e22c93d45898104a412b483/conf/.env.production.sample#L92-L107

**Comment by voxofox** [comment]
> Hi guys I'm having this error this chapter present the diversity of social sciences sciences
> 
> which part of .env should change??

Did you solve this issue for your users? Also facing the same issue

**Comment by tio-trom** [comment]
Change LDAP_ENABLED=true  to  LDAP_ENABLED=false in /`var/www/mastodon/live/.env.production`

**Comment by jorgesat** [comment]
Hi, we are facing the same issue. Is not possible to have both LDAP and internal auth enabled at the same time?
