### ISSUE TITLE
Change password - private instance

### ISSUE THREAD

**Issue by przemyslawwilde** [YunoHost-Apps/mastodon_ynh#342]
[In relation to the problem](https://github.com/YunoHost-Apps/mastodon_ynh/issues/323)
> 
> When attempting to change my email, I go to the /auth/edit page, type in the new email I want, along with my current password, and click Save Changes. The result is the error message below. I'm not sure if this is intentional, or if it's related to the SSO features of Yunohost. The password is surely correct in this case.
> 
> ![image](https://user-images.githubusercontent.com/1760607/165660454-4c06cd9d-9c53-42b1-81a2-60d4f0cce62b.png)
> ### Context
> 
> I am using Mastodon 3.5.1 installed via Yunohost 4.3.6.3 on Debian 10.

Good evening
I also have this problem. I received a message that my password is incorrect. Is there any way to change it?
I can log in to my account correctly, but I can't change my password because I'm getting the information that it is incorrect.

![mastodon](https://user-images.githubusercontent.com/5512707/200198905-429c6082-0800-4f4f-93c2-4d0b72182fe7.png)

Mastodon | 3.5.3 on Debian 11 | YunoHost 11.0.10.2 (stable)

_Originally posted by @przemyslawwilde in https://github.com/YunoHost-Apps/mastodon_ynh/issues/323#issuecomment-1304912741_

**Comment by przemyslawwilde** [comment]
Changed by console.

**Comment by wolfskaempf** [comment]
Changing it by console also helped me, because otherwise I would not have been able to migrate my account off of my YunoHost instance.

In case anyone finds this via search, here's how you do that, since `tootctl` isn't usable without some shenanigans.

SSH into your YunoHost instance as `admin` (`ssh admin@youryunohostinstance.example.com`) and become root by running `sudo -i`.

Save the below script somewhere as `tootctl.sh` and make it executable with `chmod +x tootctl.sh`.

```bash
#!/bin/bash
cd /var/www/mastodon/live && PATH=/opt/rbenv/versions/mastodon/bin:/opt/rbenv/shims:/opt/rbenv/bin:/opt/node_n/n/versions/node/12/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin  RAILS_ENV=production bin/tootctl "$@"
```

Now you can easily use `tootctl` by calling `./tootctl.sh` instead. To get to know the options run `./tootctl.sh --help`.

To reset your account's password run `./tootctl.sh accounts modify USERNAME --reset-password` after replacing `USERNAME` with your instances username, e.g. replace it with `tom` if your full username was `@tom@social.example.com`.

Hope this helps!

**Comment by franckhomer** [comment]
Hello,

I tried but with the new password i can't connect the account.
with the user name or the user.
command and result
 _**bash ./tootctl.sh accounts modify Marcel_Picon --reset-password
OK
New password: 76315xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**_
but on my mastodon instance "email or password uncorrect"
Have you an idea ?

Thanks

**Comment by badrihippo** [comment]
Just a guess, but if the login is controlled by LDAP (as mentioned in #323) doesn't that mean the password would be controlled by LDAP too? So if you want to change your username or password, you should do them in YunoHost settings (which will be propagated here) instead of trying to change them here directly.

Changing passwords directly would make sense in cases where you're trying to move off YunoHost like @wolfskaempf was doing. But otherwise, it's going to be integrated via LDAP to the rest of YunoHost.

(Again, this is just an educated guess; please confirm if I'm right or correct me if I'm wrong)

**Comment by yalh76** [comment]
> What @badrihippo says is correct. Login is controlled by Yunohosts LDAP by default. This also means passwordmanagement should be done through Yunohost user profile settings.
> 
> To disable this feature, change LDAP_ENABLED to falsein /var/www/mastodon/live/.env.production

yep exactly
